#!/usr/bin/env python

'''
description:  Wrapper to create a single output file in LITTLE_R format from a
              list of netcdf files defined in an input file.
              Time window is extracted from obsproc.namelist.
              Uses external packages: convert_littler_single and cdo
license:      APACHE 2.0
author:       Ronald van Haren, NLeSC (r.vanharen@esciencecenter.nl)
'''

import argparse
import os
from pynetcdf2littler.wrapper_littler import wrapper_littler

if __name__=="__main__":
  # define argument menu
  description = 'Time filter Wunderground netCDF data'
  parser = argparse.ArgumentParser(description=description)
  # fill argument groups
  parser.add_argument('-f', '--filelist', help='filelist containing netcdf files',
                      default='wrapper.filelist', required=False)
  parser.add_argument('-n', '--namelist', help='netcdf2littler namelist',
                      required=True)
  parser.add_argument('-d', '--outputdir', help='outputdir',
                      required=False, default=os.getcwd())
  parser.add_argument('-o', '--outputfile', help='name of outputfile',
                      required=False, default='pynetcdf2littler.output')
  opts = parser.parse_args()

  # main function
  wrapper_littler(opts.filelist, opts.namelist, opts.outputdir,
                  opts.outputfile)
